/**Try to create promisified version of setTimeout
Create promisified version of fetch
Create promisified version of fs.readFile **/





// Async - await -The syntax in JavaScript provides a way to write asynchronous code that looks and behaves like synchronous code, making it easier to read and maintain. 

// Q: Write code using async-await 
// 1.logs hi after 1 second
// 2.logs hello 3 seconds after step 1
// 3.logs heyy there 5 seconds after step 2

function setTimeoutPromisified (duration){
    return new Promise

}
