/** sum of two numbers */
/*function to add two numbers and return the sum*/

function sum(a,b){
    return a +b;
}
// calling the function and the result in a variable
let ans = sum(2,3)
// print hte result
console.log(ans);

function add (j,k) {
    return j + k ;

}
let ans1 = add(6,8);
console.log(ans1);

//q2. function to Find the sum from 1 to a number n
function sum(num){
    let ans = 0;
}




// function to calculate  the sum of number from 1 to n
function sum(num){
    // varibale to store the sume
    let ans = 0;

    // loop from 1 to n
    for (let i= 1; i<= num; i++){
        // add the number to the sum
        ans = ans + i;
    }
    // return the sum
    return ans;

}
// calling the function and the result in a variable

let ans = ans(5);

// print the result
console.log(ans);